"""Forensic report generation in HTML and JSON formats.

Produces comprehensive incident reports from alert data,
evidence, timeline, and intel results.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.core.config import AppConfig
from src.core.exceptions import ForensicError
from src.core.models import Alert

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Incident Report - {{ alert_uid }}</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; margin: 2em; background: #1a1a2e; color: #eee; }
        h1 { color: #e94560; border-bottom: 2px solid #e94560; padding-bottom: 0.5em; }
        h2 { color: #0f3460; background: #16213e; padding: 0.5em; border-radius: 4px; }
        .severity-CRITICAL { color: #ff0000; font-weight: bold; }
        .severity-HIGH { color: #ff6600; font-weight: bold; }
        .severity-MEDIUM { color: #ffcc00; }
        .severity-LOW { color: #66ccff; }
        .severity-INFO { color: #aaa; }
        table { border-collapse: collapse; width: 100%%; margin: 1em 0; }
        th, td { border: 1px solid #333; padding: 8px; text-align: left; }
        th { background: #16213e; }
        tr:nth-child(even) { background: #1a1a3e; }
        .timeline-entry { padding: 0.5em; margin: 0.3em 0; border-left: 3px solid #0f3460; padding-left: 1em; }
        .timeline-primary { border-left-color: #e94560; background: #2a1a2e; }
        .meta { color: #888; font-size: 0.9em; }
        pre { background: #0d1117; padding: 1em; border-radius: 4px; overflow-x: auto; }
        .footer { margin-top: 3em; padding-top: 1em; border-top: 1px solid #333; color: #666; }
    </style>
</head>
<body>
    <h1>Incident Report</h1>
    <p class="meta">Generated: {{ generated_at }} | Alert UID: {{ alert_uid }}</p>

    <h2>Alert Summary</h2>
    <table>
        <tr><th>Title</th><td>{{ title }}</td></tr>
        <tr><th>Severity</th><td class="severity-{{ severity }}">{{ severity }}</td></tr>
        <tr><th>Score</th><td>{{ score }}/100</td></tr>
        <tr><th>Type</th><td>{{ alert_type }}</td></tr>
        <tr><th>Status</th><td>{{ status }}</td></tr>
        <tr><th>Created</th><td>{{ created_at }}</td></tr>
        <tr><th>Description</th><td>{{ description }}</td></tr>
    </table>

    {% if source_ip or dest_ip %}
    <h2>Network Details</h2>
    <table>
        {% if source_ip %}<tr><th>Source IP</th><td>{{ source_ip }}{% if source_port %}:{{ source_port }}{% endif %}</td></tr>{% endif %}
        {% if dest_ip %}<tr><th>Destination IP</th><td>{{ dest_ip }}{% if dest_port %}:{{ dest_port }}{% endif %}</td></tr>{% endif %}
        {% if process_name %}<tr><th>Process</th><td>{{ process_name }} (PID {{ process_pid }})</td></tr>{% endif %}
    </table>
    {% endif %}

    {% if intel_data %}
    <h2>Threat Intelligence</h2>
    <table>
        {% for key, value in intel_data.items() %}
        <tr><th>{{ key }}</th><td>{{ value }}</td></tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if timeline %}
    <h2>Event Timeline</h2>
    {% for entry in timeline %}
    <div class="timeline-entry {% if entry.is_primary %}timeline-primary{% endif %}">
        <strong>#{{ entry.sequence_number }}</strong> [{{ entry.timestamp }}]
        {{ entry.description }}
        {% if entry.is_primary %}<em>(Primary trigger)</em>{% endif %}
    </div>
    {% endfor %}
    {% endif %}

    {% if evidence_files %}
    <h2>Evidence Files</h2>
    <table>
        <tr><th>Type</th><th>File</th><th>SHA-256</th><th>Collected</th></tr>
        {% for ev in evidence_files %}
        <tr>
            <td>{{ ev.evidence_type }}</td>
            <td>{{ ev.file_path }}</td>
            <td><code>{{ ev.sha256_hash[:16] }}...</code></td>
            <td>{{ ev.collected_at }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if response_actions %}
    <h2>Response Actions</h2>
    <table>
        <tr><th>Action</th><th>Status</th><th>Parameters</th></tr>
        {% for action in response_actions %}
        <tr>
            <td>{{ action.action_type }}</td>
            <td>{{ action.status }}</td>
            <td><code>{{ action.parameters }}</code></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    <div class="footer">
        <p>Report generated by Cyber Attack Detection v1.0.1</p>
    </div>
</body>
</html>"""


def generate_report(
    alert: Alert,
    config: AppConfig,
    timeline: list[dict[str, Any]] | None = None,
    evidence_files: list[dict[str, Any]] | None = None,
    intel_data: dict[str, Any] | None = None,
    response_actions: list[dict[str, Any]] | None = None,
) -> tuple[Path, Path]:
    """Generate forensic report in HTML and JSON formats.

    Args:
        alert: The alert to report on.
        config: Application configuration.
        timeline: Optional event timeline entries.
        evidence_files: Optional list of evidence file records.
        intel_data: Optional threat intelligence data.
        response_actions: Optional list of response actions taken.

    Returns:
        Tuple of (html_path, json_path).

    Raises:
        ForensicError: If report generation fails.
    """
    report_dir = Path(config.forensics.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    base_name = f"report_{alert.alert_uid[:8]}_{timestamp}"

    report_data = _build_report_data(
        alert, timeline, evidence_files, intel_data, response_actions
    )

    json_path = report_dir / f"{base_name}.json"
    html_path = report_dir / f"{base_name}.html"

    try:
        json_content = json.dumps(report_data, indent=2, default=str)
        json_path.write_text(json_content, encoding="utf-8")
    except OSError as exc:
        raise ForensicError(f"Failed to write JSON report: {exc}") from exc

    try:
        html_content = _render_html(report_data)
        html_path.write_text(html_content, encoding="utf-8")
    except Exception as exc:
        raise ForensicError(f"Failed to write HTML report: {exc}") from exc

    # Generate forensic ZIP archive for authorities
    zip_path = _create_forensic_archive(
        report_dir, base_name, html_path, json_path,
        alert, config, evidence_files,
    )
    if zip_path:
        logger.info("Forensic archive: %s", zip_path)

    logger.info("Reports generated: %s, %s", html_path, json_path)
    return html_path, json_path


def _create_forensic_archive(
    report_dir: Path,
    base_name: str,
    html_path: Path,
    json_path: Path,
    alert: Alert,
    config: AppConfig,
    evidence_files: list[dict[str, Any]] | None,
) -> Path | None:
    """Create a ZIP archive containing the full forensic package.

    The archive is structured for submission to law enforcement or
    incident response teams. It contains:
    - README.txt with chain-of-custody metadata
    - The HTML report (human-readable)
    - The JSON report (machine-readable)
    - All evidence files (snapshots, process lists, network, registry, timeline)
    - SHA-256 checksums of all included files (integrity verification)

    Args:
        report_dir: Output directory for the archive.
        base_name: Base filename (without extension).
        html_path: Path to the generated HTML report.
        json_path: Path to the generated JSON report.
        alert: The alert being reported.
        config: Application configuration.
        evidence_files: Evidence file records from the database.

    Returns:
        Path to the ZIP archive, or None if creation failed.
    """
    import hashlib
    import zipfile

    zip_path = report_dir / f"{base_name}.zip"
    evidence_dir = Path(config.forensics.evidence_dir) / alert.alert_uid

    try:
        checksums: list[tuple[str, str]] = []

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            # ---- README with chain-of-custody info ----
            readme = _generate_readme(alert, config, evidence_files)
            zf.writestr(f"{base_name}/README.txt", readme)

            # ---- JSON Report (machine-readable, for SIEM/SOAR tools) ----
            if json_path.exists():
                zf.write(json_path, f"{base_name}/report.json")
                checksums.append(("report.json", _sha256_file(json_path)))

            # ---- Evidence files ----
            if evidence_dir.exists():
                for evidence_file in sorted(evidence_dir.iterdir()):
                    if evidence_file.is_file():
                        arc_name = f"{base_name}/evidence/{evidence_file.name}"
                        zf.write(evidence_file, arc_name)
                        checksums.append(
                            (f"evidence/{evidence_file.name}", _sha256_file(evidence_file))
                        )

            # ---- SHA-256 checksum manifest ----
            checksum_text = "SHA-256 Integrity Checksums\n"
            checksum_text += "=" * 60 + "\n"
            checksum_text += f"Generated: {datetime.now(timezone.utc).isoformat()}\n"
            checksum_text += f"Alert UID: {alert.alert_uid}\n"
            checksum_text += "=" * 60 + "\n\n"
            for filename, sha in checksums:
                checksum_text += f"{sha}  {filename}\n"
            zf.writestr(f"{base_name}/SHA256SUMS.txt", checksum_text)

        logger.info(
            "Forensic archive created: %s (%d files, %.1f KB)",
            zip_path, len(checksums) + 2, zip_path.stat().st_size / 1024,
        )
        return zip_path

    except Exception as exc:
        logger.error("Failed to create forensic archive: %s", exc)
        return None


def _generate_readme(
    alert: Alert,
    config: AppConfig,
    evidence_files: list[dict[str, Any]] | None,
) -> str:
    """Generate a README.txt for the forensic archive.

    This file provides chain-of-custody metadata and context
    for law enforcement or incident response teams.

    Args:
        alert: The alert being reported.
        config: Application configuration.
        evidence_files: Evidence file records.

    Returns:
        README text content.
    """
    import platform
    import socket

    hostname = socket.gethostname()
    os_info = f"{platform.system()} {platform.release()} ({platform.version()})"
    timestamp = datetime.now(timezone.utc).isoformat()
    evidence_count = len(evidence_files) if evidence_files else 0

    # Extract network details with fallback to raw Suricata JSON
    raw_data = {}
    if alert.raw_event and hasattr(alert.raw_event, "data"):
        raw_data = alert.raw_event.data or {}
    raw_entry = raw_data.get("raw_entry", {})

    source_ip = alert.source_ip or raw_entry.get("src_ip") or "N/A"
    source_port = alert.source_port or raw_entry.get("src_port") or "N/A"
    dest_ip = alert.dest_ip or raw_entry.get("dest_ip") or "N/A"
    dest_port = alert.dest_port or raw_entry.get("dest_port") or "N/A"
    process_name = alert.process_name or raw_data.get("process_name") or "N/A"
    process_pid = alert.process_pid or raw_data.get("process_pid") or "N/A"
    file_path = alert.file_path or raw_data.get("file_path") or "N/A"

    readme = f"""{'=' * 70}
  FORENSIC INCIDENT REPORT
  Cyber Attack Detection v1.0.1
  Copyright (c) 2026 Loic Ader — MIT License
{'=' * 70}

ALERT INFORMATION
-----------------
  Alert UID:     {alert.alert_uid}
  Title:         {alert.title}
  Severity:      {alert.severity.value}
  Score:         {alert.score}/100
  Type:          {alert.alert_type.value}
  Status:        {alert.status.value}
  Created (UTC): {alert.created_at}
  Generated:     {timestamp}

NETWORK DETAILS
---------------
  Source IP:     {source_ip}
  Source Port:   {source_port}
  Dest IP:       {dest_ip}
  Dest Port:     {dest_port}

PROCESS DETAILS
---------------
  Process Name:  {process_name}
  Process PID:   {process_pid}
  File Path:     {file_path}

COLLECTION ENVIRONMENT
----------------------
  Hostname:      {hostname}
  OS:            {os_info}
  Collector:     Cyber Attack Detection v1.0.1

DESCRIPTION
-----------
{alert.description}

EVIDENCE FILES ({evidence_count} items)
----------------------------------------
  report.json        — Machine-readable incident data (SIEM/SOAR compatible)
  evidence/          — Collected forensic artifacts:
    system_snapshot.json      — System state at time of detection
    process_list.json         — Running processes with hashes
    network_connections.json  — Active network connections
    registry_persistence.json — Registry autostart entries
    scheduled_tasks.json      — Scheduled tasks enumeration
    timeline.json             — Event timeline reconstruction
    manifest.json             — Evidence integrity manifest
  SHA256SUMS.txt     — SHA-256 checksums for all files

INTEGRITY VERIFICATION
----------------------
  All files in this archive have SHA-256 checksums recorded
  in SHA256SUMS.txt. To verify integrity:

    1. Extract the archive
    2. Compare file hashes against SHA256SUMS.txt
    3. Any mismatch indicates tampering

CHAIN OF CUSTODY
----------------
  This archive was generated automatically by Cyber Attack
  Detection upon confirmed threat detection. Evidence was
  collected at the time of the alert and has not been modified.

  The SHA256SUMS.txt file provides cryptographic proof of
  integrity for all included files.

LEGAL NOTICE
------------
  This report is generated for authorized security monitoring
  purposes. All data was collected from systems under the
  operator's administrative control. Evidence collection
  complies with applicable cybersecurity laws.

{'=' * 70}
  End of README
{'=' * 70}
"""
    return readme


def _sha256_file(file_path: Path) -> str:
    """Compute SHA-256 hash of a file.

    Args:
        file_path: Path to the file.

    Returns:
        Hex digest string.
    """
    import hashlib

    sha256 = hashlib.sha256()
    with open(file_path, "rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()


def _build_report_data(
    alert: Alert,
    timeline: list[dict[str, Any]] | None,
    evidence_files: list[dict[str, Any]] | None,
    intel_data: dict[str, Any] | None,
    response_actions: list[dict[str, Any]] | None,
) -> dict[str, Any]:
    """Build the report data dictionary.

    Args:
        alert: The alert.
        timeline: Timeline entries.
        evidence_files: Evidence records.
        intel_data: Intel data.
        response_actions: Response actions.

    Returns:
        Complete report data dictionary.
    """
    # Extract with fallback to raw Suricata JSON
    raw_data = {}
    if alert.raw_event and hasattr(alert.raw_event, "data"):
        raw_data = alert.raw_event.data or {}
    raw_entry = raw_data.get("raw_entry", {})

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "alert_uid": alert.alert_uid,
        "title": alert.title,
        "severity": alert.severity.value,
        "score": alert.score,
        "alert_type": alert.alert_type.value,
        "status": alert.status.value,
        "created_at": alert.created_at,
        "description": alert.description,
        "source_ip": alert.source_ip or raw_entry.get("src_ip"),
        "source_port": alert.source_port or raw_entry.get("src_port"),
        "dest_ip": alert.dest_ip or raw_entry.get("dest_ip"),
        "dest_port": alert.dest_port or raw_entry.get("dest_port"),
        "process_name": alert.process_name or raw_data.get("process_name"),
        "process_pid": alert.process_pid or raw_data.get("process_pid"),
        "file_path": alert.file_path or raw_data.get("file_path"),
        "intel_data": intel_data,
        "timeline": timeline or [],
        "evidence_files": evidence_files or [],
        "response_actions": response_actions or [],
    }


def _render_html(data: dict[str, Any]) -> str:
    """Render the HTML report from data.

    Uses Jinja2 if available, falls back to simple string replacement.

    Args:
        data: Report data dictionary.

    Returns:
        HTML string.
    """
    try:
        from jinja2 import Template

        template = Template(HTML_TEMPLATE)
        return template.render(**data)
    except ImportError:
        logger.warning("Jinja2 not available, using basic HTML rendering")
        return _basic_html_render(data)


def _basic_html_render(data: dict[str, Any]) -> str:
    """Minimal HTML rendering without Jinja2.

    Args:
        data: Report data dictionary.

    Returns:
        Basic HTML string.
    """
    html = f"""<!DOCTYPE html>
<html><head><title>Incident Report - {data['alert_uid']}</title></head>
<body>
<h1>Incident Report</h1>
<p>Alert: {data['title']}</p>
<p>Severity: {data['severity']} | Score: {data['score']}/100</p>
<p>Description: {data['description']}</p>
<p>Generated: {data['generated_at']}</p>
<pre>{json.dumps(data, indent=2, default=str)}</pre>
</body></html>"""
    return html
