#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Downloads, installs, and configures Sysmon with SwiftOnSecurity config.
    Then enables the Sysmon channel in Cyber Attack Detection.

.DESCRIPTION
    1. Downloads Sysmon from Microsoft Sysinternals
    2. Downloads SwiftOnSecurity community config
    3. Installs Sysmon64 as a service
    4. Verifies installation
    5. Creates config/local.toml to enable Sysmon in Cyber Attack Detection

.NOTES
    Must be run as Administrator.
    Run: Right-click PowerShell -> Run as Administrator
    Then: .\scripts\install_sysmon.ps1
#>

$ErrorActionPreference = "Stop"

$SysmonDir = "C:\Sysmon"
$SysmonZip = "$SysmonDir\Sysmon.zip"
$SysmonExe = "$SysmonDir\Sysmon64.exe"
$ConfigFile = "$SysmonDir\sysmonconfig-export.xml"
$SysmonUrl = "https://download.sysinternals.com/files/Sysmon.zip"
$ConfigUrl = "https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml"

# Project root (relative to this script)
$ProjectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$LocalToml = Join-Path $ProjectRoot "config\local.toml"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Sysmon Installer for Cyber Attack Detection" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ---- Step 1: Check if already installed ----
$sysmonService = Get-Service -Name "Sysmon64" -ErrorAction SilentlyContinue
if ($sysmonService) {
    Write-Host "[OK] Sysmon is already installed (service: $($sysmonService.Status))" -ForegroundColor Green
    Write-Host "     To reinstall, run: sysmon64.exe -u force" -ForegroundColor Yellow
    Write-Host ""
}
else {
    # ---- Step 2: Create directory ----
    Write-Host "[1/5] Creating directory $SysmonDir..." -ForegroundColor White
    if (-not (Test-Path $SysmonDir)) {
        New-Item -ItemType Directory -Path $SysmonDir -Force | Out-Null
    }
    Write-Host "      Done." -ForegroundColor Green

    # ---- Step 3: Download Sysmon ----
    Write-Host "[2/5] Downloading Sysmon from Microsoft..." -ForegroundColor White
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $SysmonUrl -OutFile $SysmonZip -UseBasicParsing
    Write-Host "      Downloaded: $SysmonZip" -ForegroundColor Green

    # ---- Step 4: Extract ----
    Write-Host "[3/5] Extracting..." -ForegroundColor White
    Expand-Archive -Path $SysmonZip -DestinationPath $SysmonDir -Force
    Remove-Item $SysmonZip -Force
    if (-not (Test-Path $SysmonExe)) {
        Write-Host "[ERROR] Sysmon64.exe not found after extraction!" -ForegroundColor Red
        exit 1
    }
    Write-Host "      Extracted to $SysmonDir" -ForegroundColor Green

    # ---- Step 5: Download config ----
    Write-Host "[4/5] Downloading SwiftOnSecurity config..." -ForegroundColor White
    Invoke-WebRequest -Uri $ConfigUrl -OutFile $ConfigFile -UseBasicParsing
    Write-Host "      Downloaded: $ConfigFile" -ForegroundColor Green

    # ---- Step 6: Install ----
    Write-Host "[5/5] Installing Sysmon64 as a service..." -ForegroundColor White
    $proc = Start-Process -FilePath $SysmonExe -ArgumentList "-accepteula","-i",$ConfigFile -Wait -PassThru -NoNewWindow
    Write-Host "      Sysmon installer exited with code: $($proc.ExitCode)" -ForegroundColor White

    # Verify
    Start-Sleep -Seconds 3
    $sysmonService = Get-Service -Name "Sysmon64" -ErrorAction SilentlyContinue
    if ($sysmonService -and $sysmonService.Status -eq "Running") {
        Write-Host ""
        Write-Host "[OK] Sysmon64 installed and running!" -ForegroundColor Green
    }
    else {
        Write-Host "[WARNING] Sysmon service not detected. Check manually." -ForegroundColor Yellow
    }
}

# ---- Step 7: Enable Sysmon in Cyber Attack Detection config ----
Write-Host ""
Write-Host "Enabling Sysmon channel in Cyber Attack Detection..." -ForegroundColor White

$tomlContent = @"
# Local configuration override — generated by install_sysmon.ps1
# This file is merged on top of config/default.toml

[detection.eventlog]
sysmon_enabled = true
channels = ["Security", "System", "Application", "Microsoft-Windows-Sysmon/Operational"]
event_ids_of_interest = [
    # Windows Security events
    4624, 4625, 4648, 4672, 4688, 4689,
    4697, 4698, 4702, 4720, 4732,
    7045, 1102,
    # Sysmon events
    1,    # Process creation (with command line + hashes)
    3,    # Network connection
    5,    # Process terminated
    6,    # Driver loaded
    7,    # Image loaded (DLL)
    8,    # CreateRemoteThread (code injection)
    10,   # Process access (credential dumping)
    11,   # File creation
    12,   # Registry key/value create/delete
    13,   # Registry value set
    15,   # File stream creation (ADS)
    17,   # Pipe created (named pipe)
    22,   # DNS query
    23,   # File delete archived
    25,   # Process tampering
    26,   # File delete logged
]
"@

$configDir = Split-Path -Parent $LocalToml
if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
}

# Only write if local.toml doesn't exist or doesn't have sysmon config
if (Test-Path $LocalToml) {
    $existing = Get-Content $LocalToml -Raw
    if ($existing -match "sysmon_enabled") {
        Write-Host "[OK] Sysmon already configured in local.toml" -ForegroundColor Green
    }
    else {
        Add-Content -Path $LocalToml -Value "`n$tomlContent"
        Write-Host "[OK] Sysmon config appended to $LocalToml" -ForegroundColor Green
    }
}
else {
    Set-Content -Path $LocalToml -Value $tomlContent
    Write-Host "[OK] Created $LocalToml with Sysmon config" -ForegroundColor Green
}

# ---- Summary ----
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Sysmon location : $SysmonDir" -ForegroundColor White
Write-Host "  Config file     : $ConfigFile" -ForegroundColor White
Write-Host "  CAD config      : $LocalToml" -ForegroundColor White
Write-Host ""
Write-Host "  Sysmon logs are in Event Viewer:" -ForegroundColor White
Write-Host "    Applications and Services Logs" -ForegroundColor Yellow
Write-Host "      > Microsoft > Windows > Sysmon > Operational" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Restart Cyber Attack Detection to use Sysmon events." -ForegroundColor White
Write-Host ""

# ---- Quick verification ----
Write-Host "Verifying Sysmon is logging..." -ForegroundColor White
try {
    $events = Get-WinEvent -LogName "Microsoft-Windows-Sysmon/Operational" -MaxEvents 3 -ErrorAction Stop
    Write-Host "[OK] Sysmon is logging! Found $($events.Count) recent events." -ForegroundColor Green
}
catch {
    Write-Host "[INFO] No Sysmon events yet. Give it a few seconds." -ForegroundColor Yellow
}
Write-Host ""
